blueprints/home.py
import math

from flask import Blueprint, session, render_template
from bson import ObjectId

from .utils import mongo_connect, aggregate_cocktail_previews


home = Blueprint('home', __name__)


@home.route('/')
@home.route('/<page>')
@home.route('/<page>/<filter>')
def index(page=1, filter=None):
    """
    route to render the homepage
    """
    connection = mongo_connect()
    cocktails = connection["cocktails"]
    total_cocktails = cocktails.find({}).count()
    pages = math.ceil(total_cocktails/5)
    print(pages)
    user = None
    if '_id' in session:
        user = connection["users"].find_one({"_id": ObjectId(session['_id'])})
    cocktailPreviews = aggregate_cocktail_previews(cocktails, page, filter)
    return render_template('index.html',
                           cocktails=cocktailPreviews,
                           user=user,
                           current_page=page,
                           pages=pages,
                           filter=filter
                           )

templates/addcocktail.html
{% extends 'base.html' %}
{% block content %}
<main class="container">
    <div class="card">
        <div class="row my-2 mx-0 px-4 d-flex justify-content-between">
            <div>
                <h4>New Cocktail Details:</h4>
            </div>
            <div><a class="btn btn-outline-dark" href="{{ url_for('home.index') }}"><i class="fas fa-times"></i></a></div>
        </div>
        <form >
            <div class="form-group px-4">
                <label for="name">Type full name of cocktail*</label>
                <p><small id="name-error" class="text-danger"></small></p>
                <input id="name" name="name" type="text" class="form-control" 
                    placeholder="Name of Cocktail">
            </div>
            <div class="row mx-0">
                <div class="col-12 col-md-4">
                    <label for="image-preview">Image Preview</label>
                    <img id="image-preview" src="" class="img-fluid img-thumbnail" onerror="this.onerror=null;this.src='../static/images/placeholder.jpg';">
                </div>
                <div class="form-group px-4 col">
                    <label for="image-url">Please enter an image url*</label>
                    <p><small id="image-error" class="text-danger"></small></p>
                    <input id="image-url" name="image-url" type="text" class="form-control" placeholder="cocktail url" onchange="updatePreview(this)">
                </div>
            </div>
            <div class="form-group px-4">
                <label for="description">Describe your cocktail*</label>
                <p><small id="description-error" class="text-danger"></small></p>
                <textarea id="description" name="description" class="form-control"
                    placeholder="describe your cocktail"></textarea>
                
            </div>
            <div class="form-group px-4">
                <label for="flavors">Enter a list of decriptors</label>
                <div id="flavors" name="flavors" class="d-flex flex-wrap" aria-describedby="flavorHelp">
                    <div class="flavors mx-2 w-xs-50 w-md-30 w-lg-10">
                        <!-- remove inline styles later!! -->
                        <input style="width:100%; border:none" list="flavor-list" id="flavor-input" placeholder="add +"  oninput="addFlavor(this)">
                    </div>
                </div>
                <datalist id="flavor-list"></datalist>
                <small id="flavorHelp" class="form-text text-muted">please press , after each new descriptor</small>
            </div>
            <hr>
            <div id="ingredients">
                <div class="row d-flex justify-content-between mx-0 px-4">
                    <div >
                        <h4>Ingredients:</h4>
                        <p><small id="ingredients-error" class="text-danger"></small></p>
                    </div>
                    <div>
                        <h4><a class="btn btn-outline-dark" onclick="addMore()"><i id="add-1" class="far fa-plus-square"></i></a></h4>
                    </div>
                </div>
                <div id="ingredients-table">
                    <div id="ingredients-row-1" class="row mx-0 px-4">
                        <div class="col-md-4">
                            <label for="type-selector-1">Type of Ingredient</label>
                            <select id="type-selector-1" name="type-selector-1" class="form-control" onchange="getIngredients(this);">
                                <option disabled value="" selected>Choose your option</option>
                                <option value="spirit">Spirit</option>
                                <option value="garnish">Garnish</option>
                                <option value="mixer">Mixer</option>
                                <option value="others">Other</option>
                            </select>
                        </div>
                        <div id="ingredient-selector-1" class="col-md-4">
                            <label id="label-ingredient-select-1" for="ingredient-select-1" >Select Ingredient</label>
                            <input id="ingredient-select-1" name="ingredient-select-1" class="form-control" type="text" value="" placeholder="select type first" disabled>
                        </div>
                        <div class="col-md-4">
                            <label for="quantity-1">quantity</label>
                            <input id="quantity-1" name="ingredient-select-1" class="form-control" type="text" placeholder="quantity" onkeydown="next(this, event, addMore)">
                            <small id="flavorHelp" class="form-text text-muted">
                                please leave a space between quantity and units eg. 2 oz, 30 ml, 2 slices
                            </small>
                        </div>
                        <hr>
                    </div>    
                </div>
            </div>
            <div class="row mx-0 px-4">
                <h4>Equipment:</h4>
            </div>
            <div class="row mx-0 px-4">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="glass">Select Your Glass</label>
                        <select id="glass" name="glass" class="form-control">
                            <option value="" value="any" selected>Any</option>
                            <option value="collins">Collins</option>
                            <option value="martini">Martini</option>
                            <option value="hurricane">Hurricane</option>
                            <option value="margarita">Margarita</option>
                            <option value="lowball">Lowball/Rocks</option>
                            <option value="highball">Highball</option>
                            <option value="other">Other</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="form-check form-check-inline">
                            <input id="equip-1" name="equip-1" class="form-check-input" type="checkbox" value="Muddler">
                            <label class="form-check-label" for="inlineCheckbox1">Muddler</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input id="equip-2" name="equip-2" class="form-check-input" type="checkbox" value="Shaker">
                            <label class="form-check-label" for="inlineCheckbox2">Shaker</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input id="equip-3" name="equip-3" class="form-check-input" type="checkbox" value="Strainer">
                            <label class="form-check-label" for="inlineCheckbox3">Strainer</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-check form-check-inline">
                            <input id="equip-4" name="equip-4" class="form-check-input" type="checkbox" value="Lighter">
                            <label class="form-check-label" for="inlineCheckbox1">Lighter</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input id="equip-5" name="equip-5" class="form-check-input" type="checkbox" value="Blender">
                            <label class="form-check-label" for="inlineCheckbox2">Blender</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input id="equip-other" class="form-check-input" type="checkbox" value="Other" onchange="unlockOther(this)">
                            <label class="form-check-label" for="inlineCheckbox2">
                                <input id="other-equipment-name" class="form-control" type="text" placeholder="other - please specify" disabled>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="row mx-0 px-4">
                <h4>Method:</h4>
            </div>
            <div class="row d-flex justify-content-between mx-0 px-4">
                <div>

                    <p>Enter step by step instructions how to make your cocktail below.</p>
                    <p><small id="instructions-error" class="text-danger"></small></p>
                </div>
                <div><i id="add-step" class="far fa-plus-square" onclick="newStep()"></i></div>
               
            </div>
            
                <div class="row mx-0 px-4">
                    <div id = "step-by-step" class="col-12">
                        <div id="step-1" name="step-1" class="form-group">
                            <input class="form-control" type="text" placeholder="step 1" onkeydown="next(this, event, newStep)">  
                        </div>
                    </div>
                </div>

            <div class="row mx-0 px-4 d-flex justify-content-between mt-2 mb-5">
              
                    <button type="button" class="btn btn-dark" class="mb-5"><i class="fas fa-times left"></i>cancel</button>
                    <button id="add-cocktail" type="button" class="btn btn-dark" class="mb-5" onclick="getFormDetails(this, 'add')"><i class="fas fa-cocktail"></i>submit drink</button>
            </div>
        </form>
    </div>
    
</main>
{% endblock %}

{% block scripts %}
    <script src="/static/scripts/addcocktail/addingredient.js" charset="utf-8"></script>
    <script src="/static/scripts/addcocktail/getFormDetails.js" charset="utf-8"></script>
    <script src="/static/scripts/addcocktail/addAndEditControls.js" charset="utf-8"></script>
    <script>
        let addedFlavors = []
        fetch('/api/flavors/')
            .then((response) => response.json())
            .then(data => {
                data.forEach(flavor =>{
                    newFlavor = document.createElement("option");
                    newFlavor.textContent = flavor.name;
                    document.querySelector("#flavor-list").appendChild(newFlavor)
            })
        })



    </script>
{% endblock %}

templates/notfound.html
{% extends 'base.html' %}

<h1> Resource Not Found </h1>

templates/userprofile.html
{% extends 'base.html' %}
{% block content %}
<main class="container">
    <div id="user-card" data-sessionid="{{session['_id']}}" data-id="{{ user._id|string }}" class="card my-4">
        <div class="row my-2 mx-0 px-4 d-flex justify-content-between">
            <div>
                <h3> {{ user.username }}</h3>
            </div>
            <div><a class="btn btn-outline-dark" href="{{ url_for('home.index') }}"><i class="fas fa-times"></i></a></div>
        </div>
        <div class="row">
            <div id="profile" class =" col-12 col-md-4 text-center">
                {% if user._id|string == session["_id"]|string %}
                    {% if user.profile is not defined %}
                      <p>You have not yet added a profile</p>
                        <button onclick="addProfile()">click here to create your profile</button>
                        {% else %}
                        <div class="col-12">
                            <img src="{{ user.profile.profile_url }}" alt="placeholder">
                        </div>
                        <div class="col-12">
                            <h5 class="bold">bio</h5>
                            <p>{{ user.profile.profile_url }}</p>
                        </div>
                    {% endif %}
                {% else %}
                    {% if user.profile is not defined %}   
                    <p>This user does not have a profile</p>
                    {% endif %}
                {% endif %}
            </div>
            <div class=" col-12 col-md-8">
                <p>{{ user.username }}'s cocktails</p>
                <div id="users-cocktails" class="row mx-0">
                    <p>Loading cocktails...</p>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}
{% block scripts %}
<script>

let userId = document.querySelector("#user-card").dataset.id
let sessionId = document.querySelector("#user-card").dataset.sessionid


let generateMiniCocktailCard = (cocktail) =>{
    let template = document.createElement("div")
    template.className = "col-12 col-md-6"
    template.innerHTML = `
        <div id="${cocktail._id.$oid}"class="d-flex w-100">
            <div class="image-wrapper mr-2">
                <img class="img-thumbnail" style="height:100px; width:100px"
                    src="" />
            </div>
            <div class="w-100 text-right pr-2">
                <h5 class="name"><a><strong></strong></a></h5>
                <p>Date</p>
                <div class="contols d-flex justify-content-end"></div>
            </div>
  
            
        </div>
    `
    template.querySelector(".image-wrapper img").src = cocktail.image_url;
    template.querySelector(".name a").href= `/cocktail/${cocktail._id.$oid}`;
    template.querySelector(".name strong").innerText = cocktail.name;
    template.querySelector (".name").parentNode.children[1].innerText =  formatDate(new Date(cocktail.created_at));
    if (userId == sessionId){
        let editButton = document.createElement("button");
        editButton.className = "btn btn-primary btn-sm" 
        editButton.innerHTML = `edit <i class="fas fa-pen"></i>`;
        editButton.addEventListener("click", ()=>{
            editButton.innerHTML = `<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> loading...`
            window.location.replace(`/cocktail/edit/${cocktail._id.$oid}`)
        })

        let deleteButton = document.createElement("button");
        deleteButton.className = "btn btn-danger btn-sm"; 
        deleteButton.innerHTML = `delete <i class="fas fa-trash"></i>`;
        deleteButton.addEventListener("click", (e)=>{
            deleteButton.innerHTML= `<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> deleting...`
            fetch("/cocktail/delete", 
                {
                    method: 'post',
                    body: JSON.stringify({
                        "object_id": cocktail._id.$oid
                    }),
                    headers: {
                    'Content-Type': 'application/json'
                    }   
                })
            .then(() => {
                window.location.reload();
            })
        })
            
        template.querySelector(".contols").appendChild(editButton);
        template.querySelector(".contols").appendChild(deleteButton);
    }              
    return template           
}

fetch(`/api/cocktails/${userId}`)
    .then((response) => response.json())
    .then(data => {
        document.querySelector("#users-cocktails").innerHTML = ""
        data.forEach(cocktail =>{
            document.querySelector("#users-cocktails").appendChild(generateMiniCocktailCard(cocktail))
        })
    })
const addProfile = () => {
    document.querySelector("#profile").innerHTML= `<div class="row px-2">
                            <div class="col-12">
                                <img src="https://makemeacocktail.com/images/no_cocktail.png" alt="placeholder">
                            </div>
                            <div class="col-12 form-group">
                                <label for="profile-pic-url">Add an image url for your profile</label>
                                <input type="email" class="form-control" id="profile-pic-url" placeholder="Image Url">
                            </div>
                            <div class="col-12 form-group">
                                <label for="exampleFormControlTextarea1">Type a short bio about yourself for other users to read</label>
                                <textarea class="form-control" id="bio" rows="3"></textarea>
                            </div>
                            <p id="profile-error"></p>
                            <div class="col-12 mb-4">
                                <input type="button" class="modal-button" value="submit profile" onclick="nextAction()"/>
                            </div>
                        </div>`
}

const nextAction = () => {
    const profilePic= document.querySelector("#profile-pic-url").value
    const bio = document.querySelector("#bio").value
    fetch(`/user_profile/update/${userId}`, {
        method: 'POST',
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({ profile_pic: profilePic , bio: bio })
    })
    .then((response) => response.json())
    .then(data => {
        console.log(data)
        if(data.success){
            document.querySelector("#profile").innerHTML = `<div class="col-12">
                <img src="${profilePic}" alt="placeholder">
                </div>
                <div class="col-12">
                    <h5 class="bold">bio</h5>
                    <p>${bio}</p>
                </div>`   
        }
        else{
            document.querySelectorAll("#profile-error").textContent = "could not update profile"
        }
    });
}
</script>

{% endblock %}

templates/viewcocktail.html
{% extends 'base.html' %}
{% block content %}
<main class="container">
    <div class="card my-4">
        <div class="row my-2 mx-0 px-4 d-flex justify-content-between">
            <div>
                <h3 class="pink"> {{ cocktail.name }}</h3>
            </div>
            <a class="blue" href="{{ url_for('home.index') }}"><h3><i class="fas fa-times"></i></h3></a>
        </div>
        <div class="row d-flex px-4 justify-content-between">
            <div class="col-12 col-lg-6">
                <img src="{{ cocktail.image_url }}" class="img-fluid" onerror="this.onerror=null;this.src='../../static/images/placeholder.jpg';"/>
            </div>
            <div class="col-12 col-lg-6">
                <strong>Description:</strong>
                <p>{{ cocktail.description }}</p>
                <strong>Ingredients:</strong>
                <p id="spirit-tags">
                    {% for ingredient in cocktail.ingredients %}
                    <span data-id="{{ ingredient.ingredient }}" data-user="{{ session['_id'] }}" class="spirit">
                        <span>loading..</span>
                        
                        {% if session['username'] %}
                            {%  if ingredient.ingredient in user.favorite_ingredients %}
                            <i data-action="remove"></i>
                            {% else %}
                            <i data-action="add"></i>
                            {% endif %}
                        {% endif %}
                    </span>
                    {% endfor %}
                </p>
                    <strong>Flavor:</strong>
                    <p id="flavor-tags">
                        {% for flavor in cocktail.flavor_tags %}
                        <span data-id="{{ flavor }}" data-user="{{session['_id']}}" class="flavors">
                            <span>loading..</span>
                            {% if session['username'] %}
                                {%  if flavor in user.favorite_flavors %}
                                    <i data-action="remove"></i>
                                {% else %}
                                    <i data-action="add"></i>
                                {% endif %}
                            {% endif %}
                        </span>
                        {% endfor %}
                    </p>
              
            </div>
        </div>
        <hr>
        <div class="row mx-0 px-sm-4">
            <div class="col-12 col-md-6 px-sm-4">
                <h4 class="px-4 ">Ingredients</h4>
                <ul id="ingredient-list">
                    {% for ingredient in cocktail.ingredients %}
                        <li> <span data-id="{{ ingredient.ingredient }}"class="ingredient_name"></span> {{ ingredient.quantity }} {{ ingredient.units }}</li>
                    {% endfor %}
                </ul>
                    
            </div>
            <div class="col-12 col-md-6 px-sm-4">
                <h4 class="px-4">Method</h4>
                <p>
                    <ol>
                        {% for instruction in cocktail.method %}
                        <li>{{ instruction }}</li>
                        {% endfor %}
                    </ol>
                </p>
            </div>
        </div>
        <hr>
        <div class="row mx-0 px-sm-4">
            <h4 class="px-4">Comments</h4>
            <div class="new-comment col-12">
                <div class="col-12 mx-0">
                    Comment as {{ session['username'] }}
                    <div class="card col-12 px-0">
                        <div class="card-content ">
                            <textarea class="col-12"></textarea>
                        </div>
                        <div class="d-flex ">
                            <button type="button" class="btn btn-primary ml-auto" 
                            data-user="{{ session['_id'] }}" data-cocktail="{{ cocktail._id }}"
                            onclick="addComment(this)">comment</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div id="comments-area" data-cocktail="{{ cocktail._id }}">
                    Fetching Comments....
                </div>      
            </div>
        </div>
    </div>
</main>
{% endblock %}
{% block scripts %}
<script src="/static/scripts/updateTags.js" charset="utf-8"></script>

<script src="/static/scripts/managecomments.js" charset="utf-8">

   
</script>

{% endblock %}